const TASKS=[
['Fingerstyle',['IM alternation','八分音','十六分音','音量一致','I / M 不同起拍']],
['左手基本功',['拇指位置','手型','最小移動','換把 Shift','指板熟悉']],
['即興',['Root','Root＋節奏變化','Chord Tone','音階','自由嘗試、不怕錯']],
['Slap',['Thumb 力道','Pop','Ghost Note','Slap Groove']],
['歌曲',['本月主修','老師本週指定歌曲']],
['回顧',['錄影 30 秒','回看左右手','寫今日紀錄']]
];
const QUOTES=['今天不用證明自己，只要完成今天的修煉。','每一顆乾淨的音，都在塑造未來的你。','快的人很多，能持續的人很少。','錯音不是失敗，是耳朵開始工作的證據。','今天的基本功，就是未來的自由。','Groove 不靠緊張撐出來，它從放鬆裡長出來。','你不是靠一堂課變強，而是靠下一堂課前的每一天。','未來站在舞台上的你，會記得今天沒有放棄。'];
const defaultSongs=[
{id:1,name:'城市的浪漫運作',status:'已練過',progress:65,bpm:'',note:'早期曲目／slap'},
{id:2,name:'我沒有用，沒辦法給你想要的生活',status:'已練過',progress:60,bpm:'',note:'反拍'},
{id:3,name:'狂亂 Hey Kids!!',status:'已練過',progress:85,bpm:120,note:'高速 fingerstyle'},
{id:4,name:'Power',status:'暫停',progress:25,bpm:60,note:'前奏／double thumb'},
{id:5,name:'你以為',status:'7 月主修',progress:90,bpm:'',note:'Funk groove'},
{id:6,name:'Stone Cold Bush',status:'8 月主修',progress:30,bpm:'',note:'中段 slap'},
{id:7,name:'The Trooper',status:'已練過',progress:45,bpm:'',note:'三指輪指'},
{id:8,name:"U Can't Hold No Groove",status:'已練過',progress:20,bpm:'',note:'前段 technique'}
];
let db=JSON.parse(localStorage.getItem('bassJourneyDB')||'null')||{entries:{},feedback:[],songs:defaultSongs,settings:{weeklySong:'',lessonDate:''},xp:0};
let timerId=null,timerStart=null,installPrompt=null;
const $=id=>document.getElementById(id);const pad=n=>String(n).padStart(2,'0');
function localDate(d=new Date()){return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`}
function prettyDate(s){const d=new Date(s+'T12:00:00');return `${d.getMonth()+1}/${d.getDate()}（${'日一二三四五六'[d.getDay()]}）`}
function save(){localStorage.setItem('bassJourneyDB',JSON.stringify(db))}
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),1800)}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function mainSong(date=localDate()){const m=+date.slice(5,7);return m===7?'你以為':m===8?'Stone Cold Bush':'自訂下一首'}
function blankEntry(date){return{date,tasks:{},minutes:{早上:0,晚上:0,零碎:0},mood:'',energy:'',listen:'',breakthrough:'',stuck:'',video:'',journal:'',completed:false}}
function getEntry(date){return db.entries[date]||blankEntry(date)}
function setEntry(date,patch){db.entries[date]={...getEntry(date),...patch};save()}
function showPage(id){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');document.querySelectorAll('.bottom-nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===id));if(id==='homePage')renderHome();if(id==='todayPage')loadEntry($('entryDate').value||localDate());if(id==='teacherPage')renderFeedback();if(id==='songsPage')renderSongs();if(id==='statsPage')renderStats();scrollTo({top:0,behavior:'smooth'})}
function calcStreak(){let n=0,d=new Date();for(let i=0;i<400;i++){const e=db.entries[localDate(d)];if(e&&Object.values(e.tasks||{}).some(Boolean)){n++;d.setDate(d.getDate()-1)}else break}return n}
function monthHours(){const p=localDate().slice(0,7);let mins=0;Object.entries(db.entries).forEach(([k,e])=>{if(k.startsWith(p))mins+=Object.values(e.minutes||{}).reduce((a,b)=>a+(+b||0),0)});return mins/60}
function completion(e){const all=TASKS.reduce((a,[,x])=>a+x.length,0);const done=Object.values(e.tasks||{}).filter(Boolean).length;return Math.round(done/all*100)}
function renderHome(){$('todayLabel').textContent=prettyDate(localDate());$('dailyQuote').textContent=QUOTES[(new Date().getDate()-1)%QUOTES.length];$('mainSongLabel').textContent=mainSong();const xp=db.xp||0,level=Math.floor(xp/500)+1,inLevel=xp%500;$('levelLabel').textContent=`Lv.${level}`;$('xpLabel').textContent=`${inLevel} / 500 XP`;$('xpMeter').style.width=`${inLevel/5}%`;$('streakLabel').textContent=`${calcStreak()} 天`;$('monthHoursLabel').textContent=`${monthHours().toFixed(1)} 小時`;const c=completion(getEntry(localDate()));$('todayCompletionLabel').textContent=`${c}%`;$('todayCompletionMeter').style.width=`${c}%`;$('weeklySongInput').value=db.settings.weeklySong||'';$('lessonDateInput').value=db.settings.lessonDate||'';renderCountdown();renderWeeklyBars()}
function renderCountdown(){if(!db.settings.lessonDate){$('lessonCountdown').textContent='尚未設定下次上課日期';return}const a=new Date(localDate()+'T12:00:00'),b=new Date(db.settings.lessonDate+'T12:00:00'),n=Math.ceil((b-a)/86400000);$('lessonCountdown').textContent=n>=0?`距離下次上課還有 ${n} 天`:`上課日已過 ${Math.abs(n)} 天`}
function renderWeeklyBars(){let counts=Array(TASKS.length).fill(0),d=new Date();for(let i=0;i<7;i++){const e=db.entries[localDate(d)];if(e)TASKS.forEach(([,items],si)=>{if(items.some((_,ii)=>e.tasks?.[`${si}-${ii}`]))counts[si]++});d.setDate(d.getDate()-1)}$('weeklyBars').innerHTML=TASKS.map(([name],i)=>`<div class="bar-row"><span>${name}</span><div class="mini-meter"><i style="width:${counts[i]/7*100}%"></i></div><b>${counts[i]}/7</b></div>`).join('')}
function renderSessions(e){$('sessions').innerHTML=TASKS.map(([name,items],si)=>`<div class="session"><div class="session-head"><span>${name}</span><span>${items.filter((_,ii)=>e.tasks?.[`${si}-${ii}`]).length}/${items.length}</span></div><div class="task-list">${items.map((item,ii)=>`<label class="task ${e.tasks?.[`${si}-${ii}`]?'done':''}"><input type="checkbox" data-task="${si}-${ii}" ${e.tasks?.[`${si}-${ii}`]?'checked':''}/><span>${item}</span></label>`).join('')}</div></div>`).join('');document.querySelectorAll('[data-task]').forEach(x=>x.onchange=()=>{const date=$('entryDate').value,e=getEntry(date);e.tasks[x.dataset.task]=x.checked;setEntry(date,e);loadEntry(date)})}
function loadEntry(date){$('entryDate').value=date;$('entryTitle').textContent=prettyDate(date);const e=getEntry(date);renderSessions(e);['morningMins','eveningMins','extraMins'].forEach((id,i)=>$(id).value=e.minutes[['早上','晚上','零碎'][i]]||'');$('energySelect').value=e.energy||'';$('listenNote').value=e.listen||'';$('breakthroughNote').value=e.breakthrough||'';$('stuckNote').value=e.stuck||'';$('videoNote').value=e.video||'';$('journalNote').value=e.journal||'';renderMood(e.mood);updateTodayTotals()}
function renderMood(selected){$('moodRow').innerHTML=['😀','🙂','😐','😢','😭'].map(m=>`<button class="${selected===m?'selected':''}" data-mood="${m}">${m}</button>`).join('');document.querySelectorAll('[data-mood]').forEach(b=>b.onclick=()=>{const date=$('entryDate').value,e=getEntry(date);e.mood=b.dataset.mood;setEntry(date,e);renderMood(e.mood)})}
function syncTextFields(){const date=$('entryDate').value,e=getEntry(date);e.minutes={早上:+$('morningMins').value||0,晚上:+$('eveningMins').value||0,零碎:+$('extraMins').value||0};e.energy=$('energySelect').value;e.listen=$('listenNote').value;e.breakthrough=$('breakthroughNote').value;e.stuck=$('stuckNote').value;e.video=$('videoNote').value;e.journal=$('journalNote').value;setEntry(date,e);updateTodayTotals()}
function updateTodayTotals(){const e=getEntry($('entryDate').value),mins=Object.values(e.minutes||{}).reduce((a,b)=>a+(+b||0),0),c=completion(e);$('totalTodayLabel').textContent=`${mins} 分鐘`;$('completionText').textContent=`${c}%`;$('completionMeter').style.width=`${c}%`}
function finishToday(){syncTextFields();const date=$('entryDate').value,e=getEntry(date);if(!e.completed){e.completed=true;db.xp=(db.xp||0)+50;db.entries[date]=e;save()}toast(QUOTES[Math.floor(Math.random()*QUOTES.length)]);renderHome()}
function addFeedback(){const text=$('feedbackText').value.trim();if(!text)return toast('請先輸入老師回饋');db.feedback.unshift({id:Date.now(),date:$('feedbackDate').value||localDate(),category:$('feedbackCategory').value,text,action:$('feedbackAction').value.trim()});save();$('feedbackText').value='';$('feedbackAction').value='';renderFeedback();toast('已加入老師回饋')}
function renderFeedback(){$('feedbackDate').value=$('feedbackDate').value||localDate();$('feedbackList').innerHTML=db.feedback.length?db.feedback.map(x=>`<div class="item"><div class="item-head"><span class="badge">${esc(x.category)}</span><small>${prettyDate(x.date)}</small></div><p><b>「${esc(x.text)}」</b></p>${x.action?`<small>下一步：${esc(x.action)}</small>`:''}<p><button class="secondary" onclick="deleteFeedback(${x.id})">刪除</button></p></div>`).join(''):'<div class="item muted">還沒有老師回饋。</div>'}
window.deleteFeedback=id=>{db.feedback=db.feedback.filter(x=>x.id!==id);save();renderFeedback()}
function addSong(){const name=$('songName').value.trim();if(!name)return toast('請輸入歌曲名稱');db.songs.unshift({id:Date.now(),name,status:$('songStatus').value,progress:+$('songProgress').value||0,bpm:$('songBpm').value||'',note:$('songNote').value.trim()});save();['songName','songProgress','songBpm','songNote'].forEach(id=>$(id).value='');renderSongs();toast('歌曲已加入')}
function renderSongs(){$('songList').innerHTML=db.songs.length?db.songs.map((x,i)=>`<div class="item"><div class="item-head"><div><b>${esc(x.name)}</b><br><small>${esc(x.status)}${x.bpm?`｜${x.bpm} BPM`:''}</small></div><span class="badge">${x.progress||0}%</span></div><div class="song-progress"><i style="width:${Math.min(100,x.progress||0)}%"></i></div><small>${esc(x.note||'')}</small><p><button class="secondary" onclick="deleteSong(${i})">刪除</button></p></div>`).join(''):'<div class="item muted">還沒有歌曲。</div>'}
window.deleteSong=i=>{db.songs.splice(i,1);save();renderSongs()}
function drawChart(){const c=$('timeChart'),ctx=c.getContext('2d'),W=c.width,H=c.height;ctx.clearRect(0,0,W,H);let data=[],d=new Date();d.setDate(d.getDate()-13);for(let i=0;i<14;i++){const k=localDate(d),mins=Object.values(db.entries[k]?.minutes||{}).reduce((a,b)=>a+(+b||0),0);data.push({k,mins});d.setDate(d.getDate()+1)}const max=Math.max(60,...data.map(x=>x.mins));ctx.strokeStyle='#334667';ctx.beginPath();ctx.moveTo(44,18);ctx.lineTo(44,H-38);ctx.lineTo(W-18,H-38);ctx.stroke();data.forEach((x,i)=>{const step=(W-76)/14,bw=step-6,bh=x.mins/max*(H-70),px=50+i*step,py=H-38-bh;const g=ctx.createLinearGradient(0,py,0,H-38);g.addColorStop(0,'#22d3ee');g.addColorStop(1,'#8b5cf6');ctx.fillStyle=g;ctx.fillRect(px,py,bw,bh);ctx.fillStyle='#9fb0cb';ctx.font='11px sans-serif';ctx.fillText(x.k.slice(5).replace('-','/'),px,H-18)})}
function renderAchievements(){const days=Object.values(db.entries).filter(e=>Object.values(e.tasks||{}).some(Boolean)).length,hours=Object.values(db.entries).reduce((a,e)=>a+Object.values(e.minutes||{}).reduce((x,y)=>x+(+y||0),0),0)/60;const a=[['第一次修煉',days>=1],['連續 7 天',calcStreak()>=7],['累積 10 小時',hours>=10],['累積 100 小時',hours>=100],['10 筆老師回饋',db.feedback.length>=10],['10 首歌曲圖鑑',db.songs.length>=10]];$('achievementList').innerHTML=a.map(([t,ok])=>`<div class="item" style="opacity:${ok?1:.45}">${ok?'🏆':'🔒'} ${t}</div>`).join('')}
function renderStats(){drawChart();renderAchievements()}
function exportData(){const blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`Bass_Journey_backup_${localDate()}.json`;a.click();URL.revokeObjectURL(a.href)}
function resetData(){if(confirm('確定清除所有紀錄？此動作無法復原。')){localStorage.removeItem('bassJourneyDB');location.reload()}}
function timerTick(){const sec=Math.floor((Date.now()-timerStart)/1000),h=pad(Math.floor(sec/3600)),m=pad(Math.floor(sec%3600/60)),s=pad(sec%60);$('timerDisplay').textContent=`${h}:${m}:${s}`}
function startTimer(){if(timerId)return;timerStart=Date.now();timerId=setInterval(timerTick,1000);timerTick()}
function stopTimer(){if(!timerId)return;clearInterval(timerId);timerId=null;const mins=Math.max(1,Math.round((Date.now()-timerStart)/60000)),date=$('entryDate').value,e=getEntry(date),key=$('timerCategory').value;e.timerLog=e.timerLog||{};e.timerLog[key]=(e.timerLog[key]||0)+mins;e.minutes.零碎=(e.minutes.零碎||0)+mins;setEntry(date,e);$('timerDisplay').textContent='00:00:00';loadEntry(date);toast(`${key} 已記錄 ${mins} 分鐘`)}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('installBtn').hidden=false});$('installBtn').onclick=async()=>{if(installPrompt){installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;$('installBtn').hidden=true}}
document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>showPage(b.dataset.go));document.querySelectorAll('.bottom-nav button').forEach(b=>b.onclick=()=>showPage(b.dataset.page));$('weeklySongInput').oninput=e=>{db.settings.weeklySong=e.target.value;save()};$('lessonDateInput').onchange=e=>{db.settings.lessonDate=e.target.value;save();renderHome()};$('entryDate').onchange=e=>loadEntry(e.target.value);$('goTodayBtn').onclick=()=>loadEntry(localDate());['morningMins','eveningMins','extraMins','energySelect','listenNote','breakthroughNote','stuckNote','videoNote','journalNote'].forEach(id=>$(id).oninput=syncTextFields);$('finishTodayBtn').onclick=finishToday;$('addFeedbackBtn').onclick=addFeedback;$('addSongBtn').onclick=addSong;$('exportBtn').onclick=exportData;$('resetBtn').onclick=resetData;$('timerStart').onclick=startTimer;$('timerStop').onclick=stopTimer;$('importFile').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{db=JSON.parse(r.result);save();renderHome();toast('備份已匯入')}catch{toast('檔案格式錯誤')}};r.readAsText(f)};
$('entryDate').value=localDate();$('feedbackDate').value=localDate();renderHome();loadEntry(localDate());if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');
